source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
	pod 'MOBFoundation'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapNavi'
    pod 'MJExtension'
    pod 'SDWebImage', '3.7.5'
end

target 'WeexMapcomponent' do
    common
end


